# Generated by Django 5.1.3 on 2024-11-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_circuitstep_circuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
