# Generated by Django 5.1.3 on 2024-11-22 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_equipment_last_maintenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='reservation_date',
            new_name='reservation_datetime',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='reservation_time',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
